apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[{"apiVersion": "crdb.cockroachlabs.com/v1alpha1", "kind": "CrdbCluster", "metadata": {"name": "crdb-tls-enabled"}, "spec": {"dataStore": {"emptyDir": {}}, "tlsEnabled": true, "nodes": 3}}]'
    capabilities: Full Lifecycle
    categories: Database
    certified: '''true'''
    containerImage: registry.connect.redhat.com/cockroachdb/cockroachdb-operator:v1.0.0-rc.2
    createdAt: 2020-09-03T16:13:29Z
    description: CockroachDB Operator
    operators.operatorframework.io/internal-objects: '["crdbclusters.crdb.cockroachlabs.com"]'
    repository: https://github.com/cockroachdb/cockroach-operator
    support: Cockroach Labs
  name: cockroach-operator.v1.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
      - kind: CrdbCluster
        name: crdbclusters.crdb.cockroachlabs.com
        version: v1alpha1
  description: This operator launches and manages a 3+ node cluster of CockroachDB.
  displayName: Cockroach Operator
  icon:
    - base64data: PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzMS44MiAzMiIgd2lkdGg9IjI0ODYiIGhlaWdodD0iMjUwMCI+PHRpdGxlPkNMPC90aXRsZT48cGF0aCBkPSJNMTkuNDIgOS4xN2ExNS4zOSAxNS4zOSAwIDAgMS0zLjUxLjQgMTUuNDYgMTUuNDYgMCAwIDEtMy41MS0uNCAxNS42MyAxNS42MyAwIDAgMSAzLjUxLTMuOTEgMTUuNzEgMTUuNzEgMCAwIDEgMy41MSAzLjkxek0zMCAuNTdBMTcuMjIgMTcuMjIgMCAwIDAgMjUuNTkgMGExNy40IDE3LjQgMCAwIDAtOS42OCAyLjkzQTE3LjM4IDE3LjM4IDAgMCAwIDYuMjMgMGExNy4yMiAxNy4yMiAwIDAgMC00LjQ0LjU3QTE2LjIyIDE2LjIyIDAgMCAwIDAgMS4xM2EuMDcuMDcgMCAwIDAgMCAuMDkgMTcuMzIgMTcuMzIgMCAwIDAgLjgzIDEuNTcuMDcuMDcgMCAwIDAgLjA4IDAgMTYuMzkgMTYuMzkgMCAwIDEgMS44MS0uNTQgMTUuNjUgMTUuNjUgMCAwIDEgMTEuNTkgMS44OCAxNy41MiAxNy41MiAwIDAgMC0zLjc4IDQuNDhjLS4yLjMyLS4zNy42NS0uNTUgMXMtLjIyLjQ1LS4zMy42OS0uMzEuNzItLjQ0IDEuMDhhMTcuNDYgMTcuNDYgMCAwIDAgNC4yOSAxOC43Yy4yNi4yNS41My40OS44MS43M3MuNDQuMzcuNjcuNTQuNTkuNDQuODkuNjRhLjA3LjA3IDAgMCAwIC4wOCAwYy4zLS4yMS42LS40Mi44OS0uNjRzLjQ1LS4zNS42Ny0uNTQuNTUtLjQ4LjgxLS43M2ExNy40NSAxNy40NSAwIDAgMCA1LjM4LTEyLjYxIDE3LjM5IDE3LjM5IDAgMCAwLTEuMDktNi4wOWMtLjE0LS4zNy0uMjktLjczLS40NS0xLjA5cy0uMjItLjQ3LS4zMy0uNjktLjM1LS42Ni0uNTUtMWExNy42MSAxNy42MSAwIDAgMC0zLjc4LTQuNDggMTUuNjUgMTUuNjUgMCAwIDEgMTEuNi0xLjg0IDE2LjEzIDE2LjEzIDAgMCAxIDEuODEuNTQuMDcuMDcgMCAwIDAgLjA4IDBxLjQ0LS43Ni44Mi0xLjU2YS4wNy4wNyAwIDAgMCAwLS4wOUExNi44OSAxNi44OSAwIDAgMCAzMCAuNTd6IiBmaWxsPSIjMTUxZjM0Ii8+PHBhdGggZD0iTTIxLjgyIDE3LjQ3YTE1LjUxIDE1LjUxIDAgMCAxLTQuMjUgMTAuNjkgMTUuNjYgMTUuNjYgMCAwIDEtLjcyLTQuNjggMTUuNSAxNS41IDAgMCAxIDQuMjUtMTAuNjkgMTUuNjIgMTUuNjIgMCAwIDEgLjcyIDQuNjgiIGZpbGw9IiMzNDg1NDAiLz48cGF0aCBkPSJNMTUgMjMuNDhhMTUuNTUgMTUuNTUgMCAwIDEtLjcyIDQuNjggMTUuNTQgMTUuNTQgMCAwIDEtMy41My0xNS4zN0ExNS41IDE1LjUgMCAwIDEgMTUgMjMuNDgiIGZpbGw9IiM3ZGJjNDIiLz48L3N2Zz4=
      mediatype: image/svg+xml
  install:
    spec:
      clusterPermissions:
        - rules:
            - apiGroups:
                - apps
              resources:
                - statefulsets
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - apps
              resources:
                - statefulsets/status
              verbs:
                - get
                - patch
                - update
            - apiGroups:
                - certificates.k8s.io
              resources:
                - certificatesigningrequests
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - watch
            - apiGroups:
                - certificates.k8s.io
              resources:
                - certificatesigningrequests/approval
              verbs:
                - update
            - apiGroups:
                - certificates.k8s.io
              resources:
                - certificatesigningrequests/status
              verbs:
                - get
                - patch
                - update
            - apiGroups:
                - ""
              resources:
                - configmaps
              verbs:
                - get
            - apiGroups:
                - ""
              resources:
                - configmaps/status
              verbs:
                - get
            - apiGroups:
                - ""
              resources:
                - pods/exec
              verbs:
                - create
            - apiGroups:
                - ""
              resources:
                - secrets
              verbs:
                - create
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - ""
              resources:
                - services
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - ""
              resources:
                - services/status
              verbs:
                - get
                - patch
                - update
            - apiGroups:
                - crdb.cockroachlabs.com
              resources:
                - crdbclusters
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - policy
              resources:
                - poddisruptionbudgets
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - crdb.cockroachlabs.com
              resources:
                - crdbclusters/status
              verbs:
                - get
                - patch
                - update
          serviceAccountName: cockroach-operator-role
        - rules:
            - apiGroups:
                - apps
              resources:
                - statefulsets
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - apps
              resources:
                - statefulsets/finalizers
              verbs:
                - get
                - list
                - watch
            - apiGroups:
                - apps
              resources:
                - statefulsets/status
              verbs:
                - get
                - patch
                - update
            - apiGroups:
                - certificates.k8s.io
              resources:
                - certificatesigningrequests
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - watch
            - apiGroups:
                - certificates.k8s.io
              resources:
                - certificatesigningrequests/approval
              verbs:
                - update
            - apiGroups:
                - certificates.k8s.io
              resources:
                - certificatesigningrequests/status
              verbs:
                - get
                - patch
                - update
            - apiGroups:
                - ""
              resources:
                - configmaps
              verbs:
                - get
            - apiGroups:
                - ""
              resources:
                - configmaps/status
              verbs:
                - get
            - apiGroups:
                - ""
              resources:
                - pods/exec
              verbs:
                - create
            - apiGroups:
                - ""
              resources:
                - secrets
              verbs:
                - create
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - ""
              resources:
                - services
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - ""
              resources:
                - services/finalizers
              verbs:
                - get
                - list
                - watch
            - apiGroups:
                - ""
              resources:
                - services/status
              verbs:
                - get
                - patch
                - update
            - apiGroups:
                - crdb.cockroachlabs.com
              resources:
                - crdbclusters
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - crdb.cockroachlabs.com
              resources:
                - crdbclusters/status
              verbs:
                - get
                - patch
                - update
            - apiGroups:
                - policy
              resources:
                - poddisruptionbudgets
              verbs:
                - create
                - delete
                - get
                - list
                - patch
                - update
                - watch
            - apiGroups:
                - policy
              resources:
                - poddisruptionbudgets/finalizers
              verbs:
                - get
                - list
                - watch
            - apiGroups:
                - policy
              resources:
                - poddisruptionbudgets/status
              verbs:
                - get
          serviceAccountName: cockroach-operator
      deployments:
        - name: cockroach-operator
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: cockroach-operator
            strategy: {}
            template:
              metadata:
                labels:
                  app: cockroach-operator
              spec:
                containers:
                  - env:
                      - name: WATCH_NAMESPACE
                        value:
                    image: cockroach-operator:placeholder
                    imagePullPolicy: IfNotPresent
                    name: cockroach-operator
                    resources:
                      requests:
                        cpu: 10m
                        memory: 32Mi
                serviceAccountName: cockroach-operator-default
    strategy: deployment
  installModes:
    - supported: true
      type: OwnNamespace
    - supported: true
      type: SingleNamespace
    - supported: false
      type: MultiNamespace
    - supported: true
      type: AllNamespaces
  keywords:
    - todo
  links:
    - name: Documentation
      url: https://docs.cockroachlabs.com
    - name: Operator Source
      url: https://github.com/cockroachdb/cockroach-operator
    - name: Cockroach Labs
      url: https://www.cockroachlabs.com
  maturity: alpha
  provider:
    name: Cockroach Labs
  version: 1.0.0
  maintainers:
    - email: support@cockroachlabs.com
      name: Cockroach Labs Support
