# Copyright 2020 The Cockroach Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# RBAC Definition (ServiceAccount, and ClusterRoleBinding)
# ClusterRole is in rbac.ayml


---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cockroach-operator-default
  namespace: default
  annotations:
  labels:
    app: cockroach-operator

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: cockroach-operator-default
  labels:
    app: cockroach-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cockroach-operator-role
subjects:
  - name: cockroach-operator-default
    namespace: default
    kind: ServiceAccount

# Operator Deployment Definition:
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cockroach-operator
  namespace: default
  labels:
    app: cockroach-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cockroach-operator
  template:
    metadata:
      labels:
        app: cockroach-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cockroach-operator
  template:
    metadata:
      labels:
        app: cockroach-operator
    spec:
      serviceAccountName: cockroach-operator-default
      containers:
        - name: cockroach-operator
          # image name is replaced by kustomize
          image: "cockroach-operator:placeholder"
          imagePullPolicy: IfNotPresent
          env:
          - name: WATCH_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: OPERATOR_NAME
            value: cockroachdb
          - name: RELATED_IMAGE_COCKROACH
            value: "registry.connect.redhat.com/cockroachdb/cockroach:v20.1.4"
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
