apiVersion: crdb.cockroachlabs.com/v1alpha1
kind: CrdbCluster
metadata:
  name: crdb-tls-enabled
  # I think we have to have an operator in this namespace
  # namespace: playground
spec:
  dataStore:
    emptyDir: {}
  tlsEnabled: true
  image: cockroachdb/cockroach:v20.1.3 
  nodes: 3
